Repository myf-technology/myf-mobile, pull requests merged in 2022-08, with the labels that each got.

#7 migrate components and register flow
  App.tsx
  __tests__/App-test.tsx
  package.json
  src/components/Icon/_components/IconFactory/index.tsx
  src/components/Icon/_components/IconFactory/types.ts
  src/components/Icon/iconLib/icons/ArrowForward.tsx
  src/components/Icon/iconLib/index.tsx
  src/components/Icon/index.tsx
  src/components/Icon/types.ts
  src/components/Input/_components/Input/index.tsx
  src/components/Input/_components/Input/styles.ts
  src/components/Input/_components/Input/types.ts
  src/components/Input/_components/InvisibleInput/index.tsx
  src/components/Input/_components/InvisibleInput/types.ts
  src/components/Input/index.ts
  src/components/Layout/_components/Layout/index.tsx
  src/components/Layout/_components/Layout/styles.ts
  src/components/Layout/_components/Layout/types.ts
  src/components/Layout/index.ts
  src/components/Spacer/index.tsx
  src/components/Text/index.tsx
  src/components/Text/styles.ts
  src/components/Text/types.ts
  src/components/index.ts
  src/constants/Colors.ts
  src/constants/Layout.ts
  src/constants/Responsive.ts
  src/constants/Typography.ts
  src/constants/index.ts
  src/enums/TestIds.ts
  src/enums/index.ts
  src/views/Register/EmailName/index.tsx
  src/views/Register/EmailName/types.ts
  src/views/Register/index.tsx
  yarn.lock
Labels: master

#8 bring: first step done
  App.tsx
  ios/Podfile.lock
  ios/myf_mobile.xcodeproj/project.pbxproj
  ios/myf_mobile.xcworkspace/contents.xcworkspacedata
  src/components/Input/_components/Input/index.tsx
  src/components/KeyConfirm/_components/WhiteLine/index.tsx
  src/components/KeyConfirm/index.tsx
  src/components/KeyConfirm/styles.ts
  src/components/KeyConfirm/types.ts
  src/components/PathLink/index.tsx
  src/components/PathLink/types.ts
  src/views/Register/Password/index.tsx
  src/views/Register/Password/styles.ts
  src/views/Register/Password/types.ts
  src/views/Register/VerifyEmail/_helpers/Countdown.tsx
  src/views/Register/VerifyEmail/index.tsx
  src/views/Register/VerifyEmail/styles.ts
Labels: master

#9 feature: updated commit
  package.json
  src/components/Input/_components/Input/index.tsx
  src/components/Input/_components/Input/styles.ts
  src/components/Input/_components/Input/types.ts
  yarn.lock
Labels: master, component

#10 Bring/old dashboard as new
  .gitignore
  App.tsx
  babel.config.js
  index.js
  ios/Podfile.lock
  package.json
  src/components/Button/__tests__/Button.spec.tsx
  src/components/Button/helpers/textColorMapper.ts
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/views/Dashboard/Incoming/index.tsx
  src/views/Dashboard/_components/Agenda/index.tsx
  src/views/Dashboard/_components/Agenda/styles.ts
  src/views/Dashboard/_components/Balance/index.tsx
  src/views/Dashboard/_components/Category/index.tsx
  src/views/Dashboard/_components/HiddenNotify/index.tsx
  src/views/Dashboard/_components/InCategory/InCategory.tsx
  src/views/Dashboard/_components/InCategory/inCategories.ts
  src/views/Dashboard/_components/PennyInOut/index.tsx
  src/views/Dashboard/index.tsx
  src/views/Dashboard/styles.ts
  src/views/Register/VerifyEmail/index.tsx
  yarn.lock
Labels: master

#11 Feature/button refactor
  App.tsx
  package.json
  src/components/Button/__tests__/Button.spec.tsx
  src/components/Button/helpers/textColorMapper.ts
  src/components/Button/index.tsx
  src/components/Button/styles.ts
  src/components/Button/types.ts
  src/components/Input/_components/Input/index.tsx
  src/components/Input/_components/Input/types.ts
  src/components/Input/index.ts
  src/components/Text/index.tsx
  src/components/index.ts
  src/views/Register/EmailName/index.tsx
  src/views/Register/Password/index.tsx
Labels: master, component

#12 Feature/refactor dashboard
  App.tsx
  src/components/Input/_components/Input/index.tsx
  src/components/Input/_components/Input/styles.ts
  src/components/Text/index.tsx
  src/components/Text/styles.ts
  src/constants/Typography.ts
  src/views/Dashboard/Incoming/index.tsx
  src/views/Dashboard/_components/Agenda/index.tsx
  src/views/Dashboard/_components/Balance/index.tsx
  src/views/Dashboard/_components/Category/index.tsx
  src/views/Dashboard/_components/CategoryListBottomSheet/index.tsx
  src/views/Dashboard/_components/CategoryListBottomSheet/styles.ts
  src/views/Dashboard/_components/CategoryListBottomSheet/types.ts
  src/views/Dashboard/_components/CreateBalanceForm/_helpers/initialFormData.ts
  src/views/Dashboard/_components/CreateBalanceForm/index.tsx
  src/views/Dashboard/_components/CreateBalanceForm/styles.ts
  src/views/Dashboard/_components/CreateBalanceForm/types.ts
  src/views/Dashboard/_components/Header/_components/Agenda/index.tsx
  src/views/Dashboard/_components/Header/_components/Agenda/styles.ts
  src/views/Dashboard/_components/Header/_components/Balance/index.tsx
  src/views/Dashboard/_components/Header/_components/HiddenNotify/index.tsx
  src/views/Dashboard/_components/Header/index.tsx
  src/views/Dashboard/_components/Header/styles.ts
  src/views/Dashboard/_components/HiddenNotify/index.tsx
  src/views/Dashboard/_components/index.tsx
  src/views/Dashboard/index.tsx
  src/views/Dashboard/index.tsx.old
  src/views/Dashboard/styles.ts
Labels: New view, master

#13 feat: create new category creation view
  App.tsx
  src/components/Button/styles.ts
  src/components/CreateCategorySheet/index.tsx
  src/components/CreateCategorySheet/style.ts
  src/components/CreateCategorySheet/types.ts
  src/views/Dashboard/index.tsx
Labels: master

#15 feat: set navigation for the hole app
  App.tsx
  android/app/src/main/java/com/myf_mobile/MainActivity.java
  ios/Podfile.lock
  package.json
  src/navigation/LinkingConfiguration.ts
  src/navigation/Private/Dashboard/constants.ts
  src/navigation/Private/Dashboard/index.tsx
  src/navigation/Private/Dashboard/views.tsx
  src/navigation/Private/constants.ts
  src/navigation/Private/index.tsx
  src/navigation/Private/views.ts
  src/navigation/constants.ts
  src/navigation/index.tsx
  src/views/Dashboard/styles.ts
  yarn.lock
Labels: master

#14 Feature/add redux
  App.tsx
  ios/myf_mobile/Info.plist
  package.json
  src/components/BottomSheet/CategoryListBottomSheet/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/store/actions.ts
  src/components/BottomSheet/CategoryListBottomSheet/store/initialState.ts
  src/components/BottomSheet/CategoryListBottomSheet/store/slice.ts
  src/components/BottomSheet/CategoryListBottomSheet/store/types.ts
  src/components/BottomSheet/CategoryListBottomSheet/styles.ts
  src/components/BottomSheet/CategoryListBottomSheet/types.ts
  src/hooks/useAsyncDispatch.ts
  src/services/fetchCategoryList.ts
  src/services/index.ts
  src/store/index.ts
  src/store/types.ts
  src/views/Dashboard/_components/CategoryListBottomSheet/index.tsx
  src/views/Dashboard/_components/CreateBalanceForm/index.tsx
  src/views/Dashboard/_components/index.tsx
  src/views/Dashboard/index.tsx
  src/views/Dashboard/store/slice.ts
  src/views/Login/index.tsx
  src/views/Login/styles.ts
  yarn.lock
Labels: master, action needed

#16 Feature/create warning alert
  App.tsx
  src/components/Warning/_components/Buttons/index.tsx
  src/components/Warning/_components/CloseWarning/index.tsx
  src/components/Warning/_components/TextField/index.tsx
  src/components/Warning/_components/TopIconType/index.tsx
  src/components/Warning/index.tsx
  src/components/Warning/styles.ts
  src/components/Warning/types.ts
  src/views/Dashboard/index.tsx
Labels: master

#17 Feature/create empty state category
  App.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/EmptyCategoryList/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/EmptyCategoryList/styles.ts
  src/components/BottomSheet/CategoryListBottomSheet/store/reducers/fetchCategoryListByType.ts
  src/components/BottomSheet/CategoryListBottomSheet/store/types.ts
  src/components/Icon/iconLib/icons/MyF.tsx
  src/components/Icon/iconLib/index.tsx
  src/components/Icon/types.ts
  src/navigation/Public/constants.ts
  src/navigation/Public/index.tsx
  src/navigation/Public/views.ts
  src/navigation/constants.ts
  src/navigation/index.tsx
  src/views/Home/index.tsx
  src/views/Home/styles.ts
  src/views/Home/types.ts
Labels: master

#18 Feature/create update category integration
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItem/_components/SwipeRight/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/_components/CategoryListEmpty/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/_components/CreateNewCategoryItem/index.tsx
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/_components/CreateNewCategoryItem/styles.ts
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/_components/index.ts
  src/components/BottomSheet/CategoryListBottomSheet/_components/CategoryListItems/index.tsx
  src/components/BottomSheet/ManageCategoryBottomSheet/ManageCategoryBottomSheet.tsx
  src/components/BottomSheet/ManageCategoryBottomSheet/components/ManageCategory/index.tsx
  src/components/BottomSheet/ManageCategoryBottomSheet/components/ManageCategory/styles.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/components/ManageCategory/types.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/components/ManageCategoryLoading/index.tsx
  src/components/BottomSheet/ManageCategoryBottomSheet/components/ManageCategoryLoading/styles.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/index.tsx
  src/components/BottomSheet/ManageCategoryBottomSheet/services/createCategoryService.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/services/editCategoryService.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/services/getCategoryByIdService.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/actions/createCategory.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/actions/editCategory.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/actions/getCategoryById.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/actions/manageCategoryBottomSheetControl.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/extraReducers.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/initialState.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/reducers.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/slice.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/store/types.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/style.ts
  src/components/BottomSheet/ManageCategoryBottomSheet/types.ts
  src/components/Button/styles.ts
  src/components/CreateCategorySheet/index.tsx
  src/navigation/Public/index.tsx
  src/navigation/Public/views.ts
  src/store/index.ts
  src/store/types.ts
  src/views/Dashboard/index.tsx
Labels: master, component
